# -------------
# MISCELLANEOUS
# -------------
# change prefix to ctrl+a
unbind C-b
set -g prefix C-a
bind C-a send-prefix # by repeating you can send ctrl+a
# Reload config file with 'prefix + r'
bind r source-file ~/.tmux.conf \; display "Configuration reloaded!"
# Enable mouse mode (clickable windows, panes, resizable panes)
set -g mouse on
# Keep current path when creating new windows
bind c new-window -c "#{pane_current_path}"
# Increase scrollback history limit
set -g history-limit 5000
# Set terminal title
set -g set-titles on
set -g set-titles-string "#(whoami) :: #h :: #(pwd)"
# Colour settings (optional, adjust to your preference)
set -g default-terminal "screen-256color"


# --------
# COPYMODE
# --------
# use system clipboard; need xclip for this
set -s copy-command 'xclip'
set -s set-clipboard on
# Enable vim motions in copy mode
set-window-option -g mode-keys vi
# vim style visual commands in copy mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi V send-keys -X select-line
# Smart 'y' key: If selecting, yank selection. Else yank the whole line.
bind-key -T copy-mode-vi y \
    if-shell -F "#{selection_present}" \
    "send-keys -X copy-selection-and-cancel" \
    "send-keys -X select-line ; send-keys -X copy-selection-and-cancel"
# Paste from system clipboard with Prefix + p
unbind p
bind p run "xclip -o -selection clipboard | \
            tmux load-buffer - && \
            tmux paste-buffer"


# -----
# PANES
# -----
# Set easier split pane commands, to hypehn and pipe
unbind '"'
unbind %
bind | split-window -h -c "#{pane_current_path}" # horizontal split
bind - split-window -v -c "#{pane_current_path}" # vertical split
# Pane navigation with Prefix + h, j, k, l
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
# Pane resizing with Prefix + H, J, K, L (Shift)
# note repeatable within 500ms
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
